### ISSUE TITLE
Normalize paths.

### ISSUE THREAD

**Issue by nodech** [bcoin-org/breq#4]
`brq` does not normalize paths when parsing nor when constructing from object.

Example 1. `brq('http://example.com/path/to/rss1/../rss2')`.

This will result requesting `GET /path/to/rss1/../rss2`
It would make sense to normalize this url and instead request `GET /path/to/rss2`.
This can easily achieved by using new WHATWG `URL API`.
`new URL(url)` will normalize url.

Example 2. `brq({ host: 'example.com', path: '/path/to/rss1/../rss2' });`

This won't use `url.parse` method, it will just use this path as is.

---

This is the best place to do this adjustments even though I had trouble with `bcurl` when I tried to resolve url `/wallet/../rescan`. But that worked before, because of bweb.

---

`bweb` previously was resolving paths with `Path.normalize` (which was causing problems to Windows users), even though it was receiving request: `GET /wallet/../rescan`.
Now we just remove `..` from path (that's okay, if brq requests urls correctly), while it would also make sense to redirect users or just ignore those requests, or resolve it for them on bweb, that's not a big problem. Probably `brq` is the best place to fix this issue, even though bweb could have better behavior.

**Comment by chjj** [comment]
I'm not sure we should be supporting this in the first place. Why would our design need to construct a path like `/wallet/../rescan`?
